export const LISTING_REGISTRY_ABI = [
  {
    type: "function",
    name: "createListing",
    stateMutability: "payable",
    inputs: [
      { name: "category", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "pricingToken", type: "address" },
      { name: "basePrice", type: "uint256" },
      { name: "pricingUnit", type: "string" },
      { name: "agentCardURL", type: "string" },
      { name: "expiresAt", type: "uint64" },
    ],
    outputs: [{ name: "listingId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "updateListing",
    stateMutability: "nonpayable",
    inputs: [
      { name: "listingId", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "basePrice", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pauseListing",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeListing",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getListing",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "bytes32" },
          { name: "creator", type: "address" },
          { name: "status", type: "uint8" },
          { name: "category", type: "bytes32" },
          { name: "metadataURI", type: "string" },
          { name: "pricingToken", type: "address" },
          { name: "basePrice", type: "uint256" },
          { name: "pricingUnit", type: "string" },
          { name: "agentCardURL", type: "string" },
          { name: "createdAt", type: "uint64" },
          { name: "expiresAt", type: "uint64" },
          { name: "deposit", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getAllListingIds",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    type: "function",
    name: "getListingsByCreator",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    type: "event",
    name: "ListingCreated",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "category", type: "bytes32", indexed: true },
      { name: "metadataURI", type: "string", indexed: false },
      { name: "basePrice", type: "uint256", indexed: false },
    ],
  },
] as const;

export const ESCROW_ABI = [
  {
    type: "function",
    name: "createAndFundOrder",
    stateMutability: "payable",
    inputs: [
      { name: "listingId", type: "bytes32" },
      { name: "seller", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "termsHash", type: "bytes32" },
      { name: "deadline", type: "uint64" },
    ],
    outputs: [{ name: "orderId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "confirmCompletion",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimFunds",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getOrder",
    stateMutability: "view",
    inputs: [{ name: "orderId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "bytes32" },
          { name: "listingId", type: "bytes32" },
          { name: "buyer", type: "address" },
          { name: "seller", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "protocolFee", type: "uint256" },
          { name: "termsHash", type: "bytes32" },
          { name: "status", type: "uint8" },
          { name: "createdAt", type: "uint64" },
          { name: "deadline", type: "uint64" },
          { name: "completedAt", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getOrdersByBuyer",
    stateMutability: "view",
    inputs: [{ name: "buyer", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    type: "function",
    name: "getOrdersBySeller",
    stateMutability: "view",
    inputs: [{ name: "seller", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "orderId", type: "bytes32", indexed: true },
      { name: "listingId", type: "bytes32", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "seller", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

export const REPUTATION_ABI = [
  {
    type: "function",
    name: "submitReview",
    stateMutability: "nonpayable",
    inputs: [
      { name: "orderId", type: "bytes32" },
      { name: "reviewee", type: "address" },
      { name: "rating", type: "uint8" },
      { name: "reviewURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getAverageRating",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
